appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {osx: circle}
travis:
  secure: {BINSTAR_TOKEN: XlN4awda3oHgy9VyeOYp5uHidR0l9bdZ8Y/RdVKs19WkUHPY0qZIALURC1cWaKdDbDrkSfUq7xiutl/248yR59fLUBdzLOBx+41pmoJ/PhhmZ/x+IvG2iX7RFcPQhuySi3UfZuymtvPCJ1ezXsyl/cFDHCOexaIXPQgiye6vm/QPFUSxyZ9ymvK4RcwdghteHR4wQpm6Lbr2eblarj+bGrymrq15vkUMvHpI8jJRHfYE9ItbHZ/uMlXfbltAPT1uHM96vQliaAPa544fVxZTLBNu8v/kVD0dfMo7A1BBiwvQj/6d+NAOqhVzXkRMkGdaQYnqq3hVOmLnJ8LjEGF0o+q2+7ENnQbdVZdyrnbwSzxLDS32LgisMGa4s/qSWwcBHeZJxTW7YRLOnMKKkDYBd5J9y7sFjIAAfRgTc2wfwvcqQfvLT17MXIwFOcN8VPulGOg9HKrfDDGsCMvPliqiE1hy96Y3aoc8BcVHINMdoE2QuCBKGDsYmSK2IHglJT1crdyVA8kpu9k6oif1dpLjGpa+wxI1hjGTHE0ookiLnN2rTj36vRibu2GC3jUQGPccDQHY/wzd4CfSitmSnudvGKk8PSf/WklirsTLXtgp53J7w+lXu62Aq7PoFBVhZl6/bEjbs7iihlBVHbuEMeW/EwMsWVABQBCAOhF2b40jyEs=}
shippable:
  projectId: 5c21250387b5930700bde7cd
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
